spring.application.name=comprasegura

# Conexao local. A senha deve ser definida no ambiente que inicia o Java.
spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3308/comprasegura}
spring.datasource.username=${DB_USERNAME:comprasegura_app}
spring.datasource.password=${DB_PASSWORD}

# As tabelas serao definidas na implementacao das entidades e migracoes.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
